"""Quality State Model & Real/Synthetic Separation Firewall.

Enforces four explicit data quality states:
1. REAL: Traced to physical sensor evidence via valid EvidencePackage,
   verified device signature, monotonic timestamp, and valid camera calibration.
2. SYNTHETIC: Explicitly generated by simulation, procedural generation,
   or AI inference. Must carry algorithm, seed/prompt, and confidence bound.
3. TEST DOUBLE: Hardcoded or synthesized test fixtures used to verify system behavior.
   Must NEVER be persisted to production WorldStore or served as real.
4. UNAVAILABLE: Explicit representation of missing data (never empty list, null,
   or zero-filled array).

Firewalls:
- Real data firewall: Rejects unverified synthetic data or test doubles when real is expected.
- Synthetic data firewall: Rejects synthetic data lacking required generative metadata.
- Test double firewall: Prevents test doubles from persisting to production WorldStore.
- Demo data firewall: Prevents [DEMO] assets from being treated as REAL evidence.
- Mixed scene isolation: Preserves per-entity quality tags without cross-contamination.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Iterable, List, Optional, Union


class QualityState(str, Enum):
    REAL = "REAL"
    SYNTHETIC = "SYNTHETIC"
    TEST_DOUBLE = "TEST DOUBLE"
    UNAVAILABLE = "UNAVAILABLE"


class ProductionFirewallViolation(Exception):
    """Raised when test doubles, unverified synthetic data, or demo data leak into production."""
    pass


@dataclass(frozen=True)
class SyntheticMetadata:
    """Generation parameters for synthetic assets/entities."""
    algorithm: str
    seed_or_prompt: Union[str, int]
    confidence_bound: float

    def __post_init__(self):
        if not self.algorithm or not str(self.algorithm).strip():
            raise ValueError("Synthetic data requires a non-empty algorithm name")
        if not (0.0 <= self.confidence_bound <= 1.0):
            raise ValueError(
                f"confidence_bound must be in [0.0, 1.0], got {self.confidence_bound}"
            )

    def to_dict(self) -> Dict[str, Any]:
        return {
            "algorithm": self.algorithm,
            "seed_or_prompt": self.seed_or_prompt,
            "confidence_bound": self.confidence_bound,
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "SyntheticMetadata":
        return SyntheticMetadata(
            algorithm=d["algorithm"],
            seed_or_prompt=d["seed_or_prompt"],
            confidence_bound=float(d["confidence_bound"]),
        )


@dataclass(frozen=True)
class QualityTag:
    """Explicit quality stamp attached to any entity, geometry, point cloud, or pose."""
    state: QualityState
    synthetic_metadata: Optional[SyntheticMetadata] = None
    evidence_id: Optional[str] = None
    unavailable_reason: Optional[str] = None
    is_test_double: bool = False

    def __post_init__(self):
        if self.state == QualityState.SYNTHETIC and self.synthetic_metadata is None:
            raise ValueError(
                "SYNTHETIC data requires full generation parameters "
                "(algorithm, seed/prompt, confidence_bound)"
            )
        if self.state == QualityState.UNAVAILABLE and not self.unavailable_reason:
            raise ValueError(
                "UNAVAILABLE data requires an explicit reason (never empty/null)"
            )
        if self.state == QualityState.TEST_DOUBLE and not self.is_test_double:
            object.__setattr__(self, "is_test_double", True)

    def to_dict(self) -> Dict[str, Any]:
        res: Dict[str, Any] = {
            "state": self.state.value,
            "is_test_double": self.is_test_double,
        }
        if self.synthetic_metadata:
            res["synthetic_metadata"] = self.synthetic_metadata.to_dict()
        if self.evidence_id:
            res["evidence_id"] = self.evidence_id
        if self.unavailable_reason:
            res["unavailable_reason"] = self.unavailable_reason
        return res

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "QualityTag":
        synth_meta = (
            SyntheticMetadata.from_dict(d["synthetic_metadata"])
            if d.get("synthetic_metadata")
            else None
        )
        return QualityTag(
            state=QualityState(d["state"]),
            synthetic_metadata=synth_meta,
            evidence_id=d.get("evidence_id"),
            unavailable_reason=d.get("unavailable_reason"),
            is_test_double=d.get("is_test_double", False),
        )


class RealSyntheticFirewall:
    """Enforces boundaries between real, synthetic, and test double data."""

    @staticmethod
    def classify_source_uri(uri: str) -> QualityState:
        """Determines quality state from resource identifier or descriptor."""
        normalized = uri.strip().lower()
        if "[demo]" in normalized or "demo" in normalized or "test_double" in normalized:
            return QualityState.TEST_DOUBLE
        if "synthetic" in normalized or "procedural" in normalized or "simulated" in normalized:
            return QualityState.SYNTHETIC
        return QualityState.REAL

    @classmethod
    def assert_real_evidence(cls, tag: QualityTag) -> None:
        """Rejects any data that is not verified real physical sensor evidence."""
        if tag.is_test_double or tag.state == QualityState.TEST_DOUBLE:
            raise ProductionFirewallViolation(
                f"Test double detected where real evidence is required: {tag}"
            )
        if tag.state == QualityState.SYNTHETIC:
            raise ProductionFirewallViolation(
                f"Synthetic data rejected: real physical sensor evidence required: {tag}"
            )
        if tag.state == QualityState.UNAVAILABLE:
            raise ProductionFirewallViolation(
                f"Data is UNAVAILABLE ({tag.unavailable_reason}); cannot proceed as real"
            )
        if tag.state != QualityState.REAL:
            raise ProductionFirewallViolation(
                f"Expected REAL quality state, got: {tag.state}"
            )

    @classmethod
    def assert_safe_for_production(cls, tag: QualityTag) -> None:
        """Asserts that the data is not a test double or demo fixture."""
        if tag.is_test_double or tag.state == QualityState.TEST_DOUBLE:
            raise ProductionFirewallViolation(
                "TEST DOUBLE / demo fixture cannot be persisted to production WorldStore "
                "or served as real."
            )

    @classmethod
    def verify_scene_isolation(
        cls,
        tags_before: List[QualityTag],
        tags_after: List[QualityTag],
    ) -> bool:
        """Verifies that in a mixed scene (e.g. synthetic chair in a real room),
        no element's quality state has been promoted or demoted."""
        if len(tags_before) != len(tags_after):
            raise ValueError("Scene elements count mismatch between passes")
        for b, a in zip(tags_before, tags_after):
            if b.state != a.state:
                raise ProductionFirewallViolation(
                    f"Cross-contamination detected: state changed from {b.state} to {a.state}"
                )
        return True
