"""Unreal Engine export: an editor Python script (run in the Unreal Editor's Python console / Execute Python Script).

Same delivery model as exporters/blender: the script, not a binary .umap. It spawns one StaticMeshActor per box entity
using the engine's own /Engine/BasicShapes/Cube (a 100 uu cube), scaled to the real extents. Unreal is Z-up,
LEFT-handed and in centimetres: WorldIR (x, y, z) m -> (x*100, -y*100, z*100) uu; scale = extent_cm / 100. No materials,
no blueprints, no lighting are invented. Not run in Unreal here (no Unreal install on the build machine): structure is
validated by tests (the script compiles; numbers are checked), execution is UNVERIFIED.
"""

from __future__ import annotations

from exporters.boxes import collect_boxes, fmt, make_report

_HEADER = '''"""Generated by Reality Engine (exporters/unreal). Run inside the Unreal Editor (Python enabled)."""
import unreal

CUBE = unreal.EditorAssetLibrary.load_asset("/Engine/BasicShapes/Cube.Cube")  # 100 x 100 x 100 uu


def spawn_box(label, location_cm, scale):
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.StaticMeshActor, unreal.Vector(*location_cm))
    actor.set_actor_label(label)
    actor.static_mesh_component.set_static_mesh(CUBE)
    actor.set_actor_scale3d(unreal.Vector(*scale))
    return actor


# (label, location in cm [UE frame: Z-up, left-handed], scale = extent_cm / 100)
BOXES = [
'''
_FOOTER = ''']

for _label, _loc, _scale in BOXES:
    spawn_box(_label, _loc, _scale)
'''


def export_to_unreal_script_with_report(world, artifact_store=None):
    boxes, skipped, reasons = collect_boxes(world)
    rows = []
    for b in boxes:
        x, y, z = b.center
        loc = (x * 100.0, -y * 100.0, z * 100.0)
        scale = b.size                       # extent_m * 100 cm/m / 100 uu per cube edge == extent_m
        rows.append(f"    ({b.id!r}, ({', '.join(fmt(v) for v in loc)}), ({', '.join(fmt(v) for v in scale)})),")
    content = _HEADER + "\n".join(rows) + ("\n" if rows else "") + _FOOTER
    return content, make_report("unreal", world, content, boxes, skipped, reasons)
